### ISSUE TITLE
Knowledge - Notion/Onedrive - Stuck in "Checking Authentication" page for a while(close to 10 secs) before being presented with oauth workflow.

### ISSUE THREAD

**Issue by sangee2004** [obot-platform/obot#635]
Testing with latest version - 
```
  "github.com/kubernetes-sigs/aws-encryption-provider": "24ffc614b97e06b8fdcf62de2aedad0f9f3b5e7e",
  "github.com/otto8-ai/tools": "9abc7da7146cbd8448dca8ed11fde418482f2341",
  "otto": "v0.0.0-dev+b1a78bfe"
```

**Steps to reproduce the problem:**
1. Create an agent and add knowledge files  from notion/onedrive location.

Notice that there is a big delay delay where we are stuck in "Checking Authentication" page before notion/onedrive sync is able to provide the oauth flow.

https://github.com/user-attachments/assets/1ca13e77-3cc4-4d64-8e87-c2d6db1a5fea

**Comment by cjellick** [comment]
@StrongMonkey can you explain what's going on here? Why does the `/api/agents/.../oauth-credentials/notion-data-source/login` request take so long?

**Comment by StrongMonkey** [comment]
@thedadams Know more details, but it is mostly running cred tool in the server and waiting for it to back populate oauth url. This is happening async in controller so it could take a while.

**Comment by StrongMonkey** [comment]
I found the culprit. The actuallu oauth tool is actually really fast because it is just running a binary and printing out the url. 

The things that slows things down is the controller roundtrip logic that is happening in otto, when the credential is running, we create a system thread and workspace and makes sure status are populated before proceeding. This could cause delays for several seconds. For example, when using the api, it takes 6 seconds to completed but the wait code for thread's workspace id to be populated takes about 4 seconds. 

And we are actually using multi waitfor code to wait for resources to have status populated, there is about one second delay bewteen status being written and the event is sent back from watch api.

The obvious and easy fix is to not waiting for thread workspace to be populated, as the cred tool doesn't do anything with workspace. This cuts down the time from 6s to 2s. 

And there are other places we use waitfor to watch(we watch runState in order to get url from the actually tool) and this could trigger delay too. But this is hard to change inside the framework.

**Comment by StrongMonkey** [comment]
It ends up being that we don't broadcast the changes after updating status so we don't immedietely get the change event after updating. The normal fallback timeout is every 2 seconds so it becomes pretty bad when accumalting. https://github.com/obot-platform/kinm/pull/6 should fix this.

**Comment by sangee2004** [comment]
Testing with latest build:
```
  "github.com/otto8-ai/tools": "4b351ac4e1b1c10673e8dd70a75baa92cfe41ee9",
  "gptscript": "v0.9.5-eb03680",
  "obot": "v0.0.0-dev+b8f7a867"
``

This issue is not seen anymore.
